import { Poppins, Yellowtail } from 'next/font/google';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
  variable: '--font-poppins',
})

const yellowtail = Yellowtail({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
  variable: '--font-yellowtail',
})



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${yellowtail.variable}`}>
        {children}
      </body>
    </html>
  );
}
