services:

  app:
    build: ./frontend
    container_name: app
    depends_on:
      - api
    ports:
      - "3000:3000"

  api:
    build: ./backend
    container_name: api
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "my_db"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s  

volumes:
  db_data: